import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Providers } from "./store/provider";

export const metadata: Metadata = {
  title: "Car ShowCase",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="relative">
        <Nav />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
};
export default RootLayout;
